wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.28.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744640244.764524
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 23
      4: 3.10.15
      5: 0.15.12
      6: 4.28.0.dev0
      8:
      - 5
      13: linux-x86_64
